### ISSUE TITLE
Cannot connect to desktop VSCode, ENAMETOOLONG

### ISSUE THREAD

**Issue by m2Giles** [loft-sh/devpod#1045]
**What happened?**  
When attempting to connect to desktop vscode, receive an error that ENAMETOOLONG

**What did you expect to happen instead?**  
Connection

**How can we reproduce the bug?** (as minimally and precisely as possible) 
On both docker and podman on a local host. Spin up any devpod. For example https://github.com/ublue-os/bluefin 

My *`devcontainer.json`*:
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: 0.5.6
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker/podman

**Anything else we need to know?**  
Image:
![image](https://github.com/loft-sh/devpod/assets/69128853/2840dd48-5e59-4eac-9b05-92863b424389)

When connecting from vscode instead of launching from devpod, vscode can connect.

**Comment by 89luca89** [comment]
Hi @m2Giles thanks for reporting

is VSCode installed as rpm or flatpak? 
thanks!

**Comment by 89luca89** [comment]
Just tried with both a flatpak and code installed in distrobox and both worked for me

I'm on OpenSUSE Aeon, not bluefin, but that should not be impactful

**Comment by m2Giles** [comment]
It only appears to fail on the first run when it uses the vscode URL. After the fail, I can connect to Devpod from VScode.

Browser vscode always seems to work.

VScode installed via rpm. I haven't tried the flatpak yet.

Docker and Podman were both showing the same behavior.

**Comment by 89luca89** [comment]
Try with either vscode flatpak and/or code in distrobox and let's see :+1:

**Comment by Arham4** [comment]
Hey, I don't believe in bluefin it can be uninstalled from rpm easily to then try the flatpack (unless we have both the flatpack and rpm?). It's an OCI limitation. Because of how OCI layers work, everything stays in the image and if it is removed it is basically just dereferenced in later layer in which it is removed.

**Comment by Arham4** [comment]
I decided to install the flatpak (so I have both rpm install and flatpak install on my system now). It seems devpod opened in the flatpak version, so that's good. However, upon connecting, rather than getting enametoolong, I just get this:
![image](https://github.com/loft-sh/devpod/assets/2886217/f335743d-bdad-4ce2-9cb8-4bc991c32c93)

Like the other user mentioned, VSCode on browser works fine.

**Comment by gnimmelf** [comment]
Disclaimer. I'm on DevPod v0.5.6, Linux via bluefin-dx, so I don't know if this is fixed on a later version?

ENAMETOOLONG is Node.js when the operating system rejects the creation of a new process due to the length of the 
command line being too long. 

To me this error occurs when starting VS Code on the NodeJS quickstart example from the DevPod app. 
-Closing and reopening VS Code circumvents the error.

My hunch is that DevPod issues a command with some security key as a param to the filename, and that fails in a VS Code (JS-)extension due to overall length.
-Subsequently reopening VS Code, that last used remote connection was saved, ssh is "spawned" without the full command, and voila it works. (Restarting the docker daemon doesn't work for me.)

```log
[22:04:23] debug Done creating devcontainer 
[22:04:23] info Run 'ssh my.devpod' to ssh into the devcontainer 
[22:04:23] debug No dotfiles repo specified, skipping 
[22:04:23] info Starting VSCode... 
[22:04:23] debug Error opening vscode via cli: /usr/bin/env: ‘sh’: File name too long
```

Now, if we could only see the command for starting VS Code...

Thanks,
Flemming

**Comment by bkneis** [comment]
This should be fixed as of 0.5.22

**Comment by khilmeee** [comment]
Hey guys, I encountered an issue with devpod on Bluefin DX where the error `spawn ENAMETOOLONG` pops up due to the PATH environment being excessively long. Here's how I resolved it:  

### Steps to Fix:
1. Run `which ssh` in your terminal to find the full path of the `ssh` binary.  
   ```bash
   which ssh
   # Output: /usr/bin/ssh (example)
   ```
2. Open VSCode settings and paste the path into the `remote.SSH.path` field. You can access it via this URI: `vscode://settings/remote.SSH.path`.  
![image](https://github.com/user-attachments/assets/932aabf2-371c-4336-851d-8a1c05c18d9c)


### Why This Happens:
Bluefin tends to append many entries to the `PATH` variable, which can exceed the character limit that some tools can handle. Manually setting the path helps VSCode locate the `ssh` binary without relying on a bloated `PATH`.

**Comment by 5pirit5eal** [comment]
I had the same issue and this fixed it!

**Comment by bkneis** [comment]
related to https://github.com/loft-sh/devpod/issues/1358

**Comment by bkneis** [comment]
Closing this as unfortunately I don't think there is anything devpod can do about this. I have documented the workaround in the docs. If anyone has an idea on how devpod could address this please reopen the ticket with details

**Comment by bkneis** [comment]
Closing this as unfortunately I don't think there is anything devpod can do about this. I have documented the workaround in the docs. If anyone has an idea on how devpod could address this please reopen the ticket with details
