### ISSUE TITLE
Run Python Application in PyCharm Client via JetBrains Gateway

### ISSUE THREAD

**Issue by yangliuyu** [loft-sh/devpod#1093]
I use colima to setup a local k3s and create a workspace from python quickstart example https://github.com/microsoft/vscode-remote-try-python
<img width="1312" alt="image" src="https://github.com/loft-sh/devpod/assets/1361821/f4cc0a80-f96d-458b-931a-2346cd549122">
**Is your feature request related to a problem?**  
After setup, I can jump into the container shell from the Terminal
<img width="1396" alt="image" src="https://github.com/loft-sh/devpod/assets/1361821/c393f345-50eb-4b65-b29f-5e6e0d0d93fa">
When I want to start the application, I need to setup a Run configuration
<img width="1396" alt="image" src="https://github.com/loft-sh/devpod/assets/1361821/4f9a88b2-e3bc-4c49-8e1e-4a68d58c0331">
and when I setup a Python interpreter via SSH
<img width="750" alt="image" src="https://github.com/loft-sh/devpod/assets/1361821/1422ee78-4337-4556-a81e-fee00a06b161">
got this error
<img width="828" alt="image" src="https://github.com/loft-sh/devpod/assets/1361821/7657384b-7410-4d89-b47e-8f63aeed7d6f">
The ~/.ssh/config has below content:
<img width="962" alt="image" src="https://github.com/loft-sh/devpod/assets/1361821/e609e8ff-29fb-451b-a8a5-7cf525b6158d">

**Which solution do you suggest?**  
The PyCharm client can recognize the SSH remote host and setup a remote Python Interpreter

**Which alternative solutions exist?**  
N/A

**Additional context**  
DevPod 0.5.8 | darwin | x86_64
JetBrains Gateway 2024.1.2

**Comment by schlegel11** [comment]
Hello :smiley: 

If I understand it right:
You are already connected to your container via PyCharm gateway connection?
Then why do you want to setup a remote interpreter via SSH because you are already connected via SSH to your container or better the whole PyCharm instance is a remote instance so you have to choose usually a "local interpreter" which means local in your container. 
Inside your container "vscode-remote-try-python.devpod" should be your localhost.

**Comment by yangliuyu** [comment]
Thanks for you suggestion.
You are totally correct😃, after I setup a local interpreter, it all works.
