### ISSUE TITLE
Better way to support commit signing via SSH for SSH Provider

### ISSUE THREAD

**Issue by lukas-mertens** [loft-sh/devpod#1146]
**Is your feature request related to a problem?**  
Currently it is possible to sign commits via gpg, but git allows signing via ssh as well. There should be support for doing that as well for providers like the SSH Provider.

**Which solution do you suggest?**  
Provide a way to configure an individual .gitconfig which will be placed in the container + a way to securely put ssh public keys in the container. Maybe I am missing something, but this is the way I found which isn't **that** user-friendly:
https://garden.lukmert.de/30-resources/31-how-to/31-03-devpod/signing-commits-when-using-devpod-with-ssh-provider/

**Which alternative solutions exist?**  
See my workaround:
https://garden.lukmert.de/30-resources/31-how-to/31-03-devpod/signing-commits-when-using-devpod-with-ssh-provider/

**Additional context**  
We discussed a bit on slack: https://loft-sh.slack.com/archives/C056ZDZPJ4W/p1720003846623999

**Comment by pascalbreuninger** [comment]
Hi @lukas-mertens, thanks for opening the issue. We're actively working on this, stay tuned :)

**Comment by janekbaraniewski** [comment]
hey @lukas-mertens! We've just addedd support for signing git commits using SSH keys. Devpod will automatically set this up if your local gitconfig has specified `gpg.format=ssh` and use key specified in `user.signingkey`. Signing is NOT enforced automatically - you still need to do `git commit -S ...` in order to sign your commit. 

If you want to enable it explicitly for your workspace or if you want to use a different signing key than the one specified in your local gitconfig, just add `--git-ssh-signing-key` flag to your `devpod up` command like this:

```bash
devpod up github.com/loft-sh/devpod --git-ssh-signing-key /Users/johndoe/.ssh/mykey.pub
```

Let us know what you think!
