### ISSUE TITLE
Devpod entries in .ssh/config break Include statement

### ISSUE THREAD

**Issue by maxmlr** [loft-sh/devpod#1180]
**What happened?**
When a client side SSH config file uses an `Include` statement at the beginning of the config, any new entries related to active workspaces in Devpod break the include and renders the config incomplete.
Moving the new entries of Devpod below the `Include` statement seems to mitigate the issue.

**What did you expect to happen instead?**
All SSH configs made available by the `Include` statement should not be affected by config file extension by Devpod.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`~/.ssh/config`*:
```
Include config.d/* 

Host user1
  HostName github.com
```

My *`~/.ssh/config.d/extension`*:
```
Host user2
  HostName devpod.sh
```

**Local Environment:**  
- DevPod Version: `v0.5.18`
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
Not relevant

**Anything else we need to know?**  
No

**Comment by pascalbreuninger** [comment]
Hi @maxmlr, thanks for opening the issue. You're right, apparently every include block after the first host will be interpreted in the context of the host instead of globally. 
This should be fixed with #1181 

Until then you can use the `--ssh-config` flag (or the `SSH_CONFIG_PATH` context option) to write all DevPod workspace entries to a separate config file.
