### ISSUE TITLE
Can not pull  docker.io/library/devcontainer:latest

### ISSUE THREAD

**Issue by MimeLyc** [loft-sh/devpod#1206]
**What happened?**  
I wanted to dev runc in a devcontainer, so I added such devcontainer.json content to it:
```json
{
  "name": "runc",
  "build": {
    "context": "..",
    "dockerfile": "../Dockerfile",
    "target": "devcontainer"
  },
  "workspaceFolder": "/go/src/github.com/opencontainers/runc",
  "workspaceount": "source=${localWorkspaceFolder},target=/go/src/github.com/opencontainers/runc,type=bind,consistency=cached",
  "remoteUser": "root",
  "runArgs": ["--privileged"],
  "customizations": {
    "vscode": {
      "extensions": ["golang.go"]
    }
  },
  "settings": {
    "go.toolsEnvVars": {
      "GOOS": "linux",
      "GOARCH": "amd64"
    }
  },
  "features": {
    "ghcr.io/devcontainers/features/git:1": {
      "version": "latest",
      "ppa": "false"
    },
    "ghcr.io/devcontainers/features/nix:1": {}
  }
}
```

Then I executed `  devpod up . --provider docker --dotfiles git@github.com:MimeLyc/${my private dotfile repo}`
and get the following error:
```
00:59:11 info #6 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
00:59:12 info ------
00:59:12 info > [internal] load metadata for docker.io/library/devcontainer:latest:
00:59:12 info ------
00:59:12 info Dockerfile-with-features:77
00:59:12 info --------------------
00:59:12 info 75 |     ENTRYPOINT [ "/prepare-cgroup-v2.sh" ]
00:59:12 info 76 |
00:59:12 info 77 | >>> FROM $_DEV_CONTAINERS_BASE_IMAGE AS dev_containers_target_stage
00:59:12 info 78 |
00:59:12 info 79 |     USER root
00:59:12 info --------------------
00:59:12 info ERROR: failed to solve: failed to resolve source metadata for docker.io/library/devcontainer:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**What did you expect to happen instead?**  
Successfully create the devcontainer.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. `git clone https://github.com/opencontainers/runc.git`
2. Mkdir .devcontainer and enter it.
3. Create devcontainer.json file and fill with above content.
4. `  devpod up . --provider docker --dotfiles {some dot file repo}`

**Local Environment:**  
- DevPod Version: v0.5.19
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**  
I can make it with the same command for the moby project.
And I can pull some public images like nginx.

**Comment by camrionnvmff** [comment]
According to the error message, docker.io/library/devcontainer: latest may not exist. You can try using other known existing images, such as Ubuntu or Alpine, to confirm that your Docker environment is working properly.

Use the correct base image
If you use a non-existent base image in devcontainerjson, you can try using a known existing base image.
Confirm Docker Hub login status
Make sure you are logged into Docker Hub and have access to the image you want to pull. You can run the following command in the terminal to log in to Docker Hub:

docker login
Check Docker environment
Confirm if your Docker environment is working properly. You can try pulling other public images to ensure that there are no issues with network connectivity and Docker configuration:

docker pull nginx
View and update Dockerfiles
Check your Dockerfile to ensure that the underlying image exists and can be accessed. Here is an example Dockerfile using a known existing base image:

#Basic image using VSCode Dev Containers
FROM mcr.microsoft.com/vscode/devcontainers/base:0-focal

#Install QPDF
RUN apt-get update && apt-get install -y qpdf

#Other configurations and commands
Testing with Docker Composer
You can use Docker Composer to test your configuration. Create a docker-compose.yml file:

version: '3'
services:
devcontainer:
build:
context: ..
dockerfile: ../Dockerfile
target: devcontainer
volumes:
- .:/ go/src/github.com/opencontainers/runc
user: root
privileged: true
Then run the following command to build and start the container:

docker-compose up --build
Confirm DevPod configuration
Ensure that your devpod commands and configuration files are correct and error free. You can try updating devpod or testing with a different version of devpod.

summary
By following the above steps, you should be able to identify and resolve the issue of not being able to pull the docker.io/library/devcontainer: latest image. Make sure to use the correct base image name and label, check if the Docker environment is functioning properly, and confirm that you have logged into Docker Hub. If the problem persists, it is recommended to provide more logs and configuration details in GitHub issues so that community members can better assist you.
In fact, Docker and Mac systems are not compatible. If you are using Mac, perhaps you can try using the Servbay tool to solve your needs.

**Comment by MimeLyc** [comment]
Tks for replying @camrionnvmff 

> Use the correct base image
The `docker.io/library/devcontainer` seems to be used in the Dockerfile generated by DevPod, and I have no idea about how to modify it.

> docker login
> docker pull nginx
> Confirm DevPod configuration or version
I have tried these methods and related info are included in the pr body.

**Comment by bkneis** [comment]
@MimeLyc I believe the issue is the build target you have specified in `devcontainer.json`. According to the [docs](https://containers.dev/implementors/json_reference/) this defines the build target to pass to the build command, i.e. `docker build --target devcontainer`. Looking at runc's Dockerfile there is no such target named "devcontainer". Testing on my machine removing the "target" attribute from your build devcontainer.json works.

Let me know if this fixes your issue :)

**Comment by MimeLyc** [comment]
@bkneis World saved! You're my hero!
