### ISSUE TITLE
Symlinked Dockerfile is not picked up

### ISSUE THREAD

**Issue by cyrus01337** [loft-sh/devpod#1293]
**What happened?**  
When attempting to spin up a devpod using a symlinked `devcontainer.json` and `Dockerfile`, the `Dockerfile` is unable to be read, while the `devcontainer.json` can be.

**What did you expect to happen instead?**  
For the contents of symlinked files to be read by `devpod`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Create a `devcontainer.json` and `Dockerfile` file in a separate directory
2. Symlink both to a project's `.devcontainer/` directory via `ln -s ...`
3. Run `devpod up <project-directory>`

My *`devcontainer.json`*:
```
{
    "name": "Neovim",
    "dockerFile": "Dockerfile",
    "workspaceFolder": "/workspace",
    "remoteUser": "neovim",
    "postCreateUser": "neovim"
}
```

**Local Environment:**  
- DevPod Version: v0.5.18
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: N/A
- Kubernetes Provider: N/A
- Local/remote provider: docker
- Custom provider: N/A

**Anything else we need to know?**  
N/A

**Comment by cyrus01337** [comment]
I see, did not know that was intended behaviour for Docker. For context, I've been trying to setup a directory of configurations including various Dockerfiles, Devcontainer configurations, etc. that I can symlink. Any changes made to the directory are automatically reflected across certain projects of mine, and I wanted to try applying that to this.

If this isn't intended to work on Docker, clearly this isn't an issue with Devpod. I'm not quite sure how to resolve my issue so if you have any ideas, I'd love to hear them. I'll close this issue however as it's unrelated to the project.

**Comment by bkneis** [comment]
@cyrus01337 one solution I can think of is to keep all your devcontainer configurations separate from the source code. For example, say you have workspace A, B and C. Each of these can live in there own repo with a Dockerfile, such is a typical set up. Then you create a repo with 3 sub directories each containing the workspaces devcontainer.json. The devcontainer json can reference an image in a registry instead of a direct Dockerfile, so these can use the images pushed from the workspace repos.

If you do not have access to a registry, you could also use git sub modules to include the workspace dockerfile in a sub directory and reference this in the devcontainer.json

**Comment by cyrus01337** [comment]
That's brilliant, never thought of that. I'll definitely try that out, thanks so much for sparing that time you didn't need to. :smile:
