### ISSUE TITLE
Error when trying to create a container for a different architecture

### ISSUE THREAD

**Issue by hferreiro** [loft-sh/devpod#1356]
**What happened?**  

Tried to run a container meant for a different architecture that the host's. `devpod up` failed with:
> Error: unknown flag: --platform linux/amd64

**What did you expect to happen instead?**  

Download the correct image.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Run the following `devcontainer.json` in an empty directory:
```
{
    "image":"mcr.microsoft.com/devcontainers/base:ubuntu",
    "runArgs": [ "--platform linux/amd64" ]
}
```

**Local Environment:**  
- DevPod Version: v0.5.21
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**
- Local/remote provider: docker (using podman)

**Comment by bkneis** [comment]
Hi @hferreiro, thanks for reporting your issue, `--platform` is a build argument and not a run argument, to build a container for a specific platform you can use `devpod build --platform ...`. I hope that helps

**Comment by hferreiro** [comment]
Is there any documentation for `devpod build`?

I'm not sure we are talking about the same tough. `podman run --platform platform` allows to emulate `platform` by using qemu, while running on an image with the same architecture as the underlying OS, IIUC.

**Comment by bkneis** [comment]
`devpod build --help` currently is the leading source. We are working on updating our docs to include more details but the help command provides a description of each of the supported parameters. In general we try to mirror docker for the build args and for up the run args. To use the emulation as you mentioned you would need to implement a podman provider. This is possible but will require some dev effort. The docker provider only supports podman since podman offers the same args as docker, but not the other way around
