### ISSUE TITLE
Allow manually specifying the prebuild image tag

### ISSUE THREAD

**Issue by oenglund** [loft-sh/devpod#1371]
**Is your feature request related to a problem?**  
Yes. We're trying to use prebuilds but the prebuild hash that devpod calculates does not match any of the prebuilt images in our registry. We could investigate why that is but for our use case, it would be easier to just manually add a hash that is used to find the prebuilt image.

**Which solution do you suggest?**  
Add a new field under `customizations.devpod` called `prebuildHash` where one can manually set a hash that devpod should use for selecting a prebuild image.

**Which alternative solutions exist?**  
Some further documentation on how the hash is generated would help investigate why the hash does not match the one generated when doing the prebuild.

**Additional context**

**Comment by bkneis** [comment]
Hi @oenglund thanks for reporting your issue! Here is the logic for calculating a prebuild hash - https://github.com/loft-sh/devpod/blob/main/pkg/devcontainer/config/prebuild.go#L18 It sounds like your getting cache misses which are not too infrequent, this is due to the high cardinality of the devcontainer. Since many files can affect the build context, resulting in a different devcontainer, prebuild hash's can be missed. We have an open ticket to support the use of a `--tag` command line arg for `devpod build` so you can do as you mentioned. If you'd like to take a crack at it I'll be happy to review the PR. If not I will try get to this soon. In the meantime, you could take a look at using a registry cache to cache individual layers so when you miss the cache, you only have to build the changes https://devpod.sh/docs/tutorials/reduce-build-times-with-cache

**Comment by manel-bc** [comment]
Hi, thanks for considering it. It would be quite helpful to have.

A questions I have is, if we can eventually specify the tag when building the image, shouldn't we be able to specify the tag when creating the Workspace as well, to be able to target that image specifically? Or how were you thinking this would work?

**Comment by bkneis** [comment]
Hi @manel-bc, the idea would be that you would do something like `devpod build --tag stable`, then in your .devcontainer.json specify the image with tag stable and perform `devpod up`

**Comment by fcaroline2020** [comment]
@bkneis here is a PR to add tags to images https://github.com/loft-sh/devpod/pull/1388/files

**Comment by pascalbreuninger** [comment]
@oenglund thanks to @fcaroline2020s contribution this is now available in the `v0.6.4` release
