### ISSUE TITLE
Docker Desktop not recognized on MacOS

### ISSUE THREAD

**Issue by codingbutstillalive** [loft-sh/devpod#356]
**What happened?**
I was using RancherDesktop. Since DevPod didn't recognize it, I uninstalled it and newly installed Docker Desktop. However, DevPod still not recognize Docker as a Provider.

**What did you expect to happen instead?**
The GUI should report that it is able to detect Docker on my Macbook.

**How can we reproduce the bug?** (as minimally and precisely as possible)
NAN

**Local Environment:**

* DevPod Version: 0.1.7
* Operating System: mac
* ARCH of the OS: i386

**DevPod Provider:**

* Local provider: docker

**Comment by pascalbreuninger** [comment]
Hi @codingbutstillalive , thanks for reporting the issue.
Can you use docker via the command line?
If so, what exactly is the error message you see in the UI

**Comment by codingbutstillalive** [comment]
I can run the docker commands (I mean the official ones) on the command line.

**Comment by pascalbreuninger** [comment]
and what is the error message you see in the ui?

**Comment by codingbutstillalive** [comment]
There is no error message in the UI. It just doesn’t show the detected
Docker daemon after its search.

Pascal Breuninger ***@***.***> schrieb am Di. 30. Mai 2023 um
07:25:

**Comment by pascalbreuninger** [comment]
would you mind providing me with the output of `which docker` and a screencast of your UI flow?
It's hard to debug otherwise because we can't repro this issue with docker desktop on any other machine

**Comment by codingbutstillalive** [comment]
Any updates on that?

Where does the UI expect to find docker? How can I check what might be the problem?

**Comment by pascalbreuninger** [comment]
On macos, if `docker` is available on the path the UI should be able to pick it up as well since it uses the CLI under the hood.
Are you able to add a provider using the CLI?
You can add the CLI to you Path from the UI via  `settings > add to path` 

What's the output of `devpod provider add docker` there?

**Comment by codingbutstillalive** [comment]
I haven‘t yet installed the CLI. It seemed optional. I wanted to first test the UI, before I install deeper integrations. So probably that is then the problem.

**Comment by pascalbreuninger** [comment]
you don't need to install the CLI seperately, the UI uses it under the hood :) You can  add it to your path from within the app in `settings > add to path`, so that it is accessible from your terminal

**Comment by codingbutstillalive** [comment]
Then I continue to have no explanation why docker isn't found.

> On macos, if `docker` is available on the path the UI should be able to pick it up as well since it uses the CLI under the hood. Are you able to add a provider using the CLI? You can add the CLI to you Path from the UI via `settings > add to path`
> 
> What's the output of `devpod provider add docker` there?

This command worked on the CLI. It detected docker and now it's also visible in the UI. My problem is solved. But the question remains why it only worked via the CLI.

Best regards,
Alive

**Comment by pascalbreuninger** [comment]
Glad it worked with the CLI

Tbh the only reason I can think of right now is your permission setup. 
What os version are you on?
How exactly did you install the desktop app?
Did you modify any permissions in your shell via config files?
What happens if you run the cli NOT from your path but directly via it's fully qualified path via `/Applications/DevPod.app/Contents/MacOS/devpod-cli provider add docker`?
