### ISSUE TITLE
~/.profile is not read

### ISSUE THREAD

**Issue by ibuildthecloud** [loft-sh/devpod#440]
**What happened?**

It appears that when a ssh session is created it is not a login session.  \~/.profile is not read but \~/.bashrc is.  I think this differs from how devcontainers works in vscode.  In my Dockerfile I have `RUN devbox shellenv --init-hook >> ~/.profile` and that profile never gets loaded.

**Comment by FabianKramm** [comment]
@ibuildthecloud we made some progress on this so that when using devpod ssh this works, however for some reason when using the vscode IDE, it is still creating non-login shells within the terminal section, so we will need to take another look at what our ssh server implementation is doing differently.
