### ISSUE TITLE
Provide flatpak package on Flathub for Linux

### ISSUE THREAD

**Issue by rugk** [loft-sh/devpod#637]
It would be nice if you could publish this as a [flatpak](https://flatpak.org/) on [flathub](https://flathub.org/) e.g.

**Is your feature request related to a problem?**  
Flatpaks are a new software distribution mechanism for Linux distros, can thus installed on any distro and are easy to update. They are easy to install _and_ update and work on all Linux distros.
Also, if you publish it on _FlatHub_ you may grow your user base given many distros include that and it is a common software source, so your app can be discovered more easily. 

**Which solution do you suggest?**  
Here is [how to get started](http://docs.flatpak.org/en/latest/getting-started.html).

**Which alternative solutions exist?**  
Snap from Ubuntu is quite similar.

However, I personally would prefer flatpak. In contrast to snap, you can also self-host it, so you stay in control, and it is widely supported. (snap is not so nice to setup in many distros and snap's security depends on AppArmor, which is not always available in many distros)
Also – in contrast to snaps – flatpaks do not only claim to be distro-independent, but [actually are](https://kamikazow.wordpress.com/2018/06/08/adoption-of-flatpak-vs-snap-2018-edition/) [and they are widely adopted](https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/).
Furthermore even [Linux Mint criticizes snap](https://blog.linuxmint.com/?p=3906), because you cannot self-host a snap server as it is proprietary and (thus) also cannot modify the packages that are served centralized by Ubuntu.

Also of course you have other installation options, but none of them is as convenient as a flatpak:
* deb/rpm -  only works on specific Linux distros/systems, and has (in the way you currently deploy it) no automatic updates
* AppImage -  is one huge binary and has no automatic updates

**Additional context**  
Technically the sandboxing thing could get tricky here. There are potential solutions though:
* either and I am not sure here, you could somehow run Docker or podman inside the flatpak (I guess not easily possible)
* you could basically, in that software version, [create flatpak sandboxes with `flatpak-spawn`  instead](https://github.com/freedomofpress/dangerzone/issues/45#issuecomment-1659156183) of Docker containers
* or you could forget the sandboxing and [use `flatpak-spawn --host`](https://docs.flatpak.org/en/latest/flatpak-command-reference.html?highlight=%22flatpak-spawn%22#flatpak-spawn) to spawn commands on the host system instead. This sandbox escape is of course only possible if you have the permissions. (and obviously requires Docker or podman or whatever you use to be installed on the host system)
* **edit:** you could also use QEMU (ref https://github.com/loft-sh/devpod/issues/335) as [VM support](https://github.com/freedomofpress/dangerzone/issues/45#issuecomment-1367389832) is possible on flatpak as e.g. [GNOME Boxes](https://github.com/flathub/org.gnome.Boxes) uses it.

**Comment by FabianKramm** [comment]
@rugk thanks for creating this issue! We considered this, but found this is too much work given that tauri doesn't support this officially (which we are dependant on). The alternative is to use either AppImage or we will provide an option soon to install from an archive (.tar.gz) like JetBrains does for their IDEs and most other applications do. I'll close this for now, if you think this really relevant for users to have, please feel free to reopen.

**Comment by westurner** [comment]
Packages and tested package management systems simplify DevOpsSec; keep the SBOM updated with the latest versions (of the *signed* repacks) of the source Releases:
- To build a package, you can either:
  - Repack a .tar.gz source tarball
  - Build from a signed git tag (and check the GPG signature first)
- When you repack, you assume responsibility for keeping that package URL and hash updated (so that everyone else gets timely security, bugfix, and feature releases; to minimize time to patch in order to quickly mitigate such issues) as the or a Package Maintainer for e.g. a Linux OS distribution.
- The CA cert bundle of the tls library of the http client secures HTTP GET retrieval of e.g. a latest.json package catalog.
- It must be possible for the client to infer from latest.json that there is a new package release to consider installing or repackaging:
  - Typical release types which may be indicated in version strings with e.g pep440: Beta, RC: Release Candidate, Release
  - [ ] devpod: latest.json: list the URL of the .tar.gz and/or the other release attachments listed on the GitHub release page
    - https://github.com/loft-sh/devpod/releases/tag/v0.3.7
      - https://github.com/loft-sh/devpod/releases/download/v0.3.7/latest.json
- a Package Maintainer [bot] SHOULD or MUST monitor for the latest releases;
  - and generate a Pull Request with the new URL and hash so that CI builds the new version of the package and runs the tests (conda-forge cf-regrotick-bot, )
  - and merge the Pull Request to release the downstream package (GitOps; conda-forge, flatpak, distro_xyz (dnf+rpm-ostree))
- The GitHub API provides a releases.json endpoint, and also actual software package repo and OCI container repo APIs:
  https://api.github.com/repos/loft-sh/devpod/releases .json
  - https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
  - https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images
- OBS Open Build System will also build and host DEB and RPM repos that work with apt, apk, yum/dnf, but then you must trust additional package repos to install specific or any packages from
- Getting devpod packages into OS package repositories would simplify container provisioning workflows (with SBOM, SLSA,)
- [ ] If a tool installs a new release of devpod, there should be a way to indicate that devpod needs to be restarted;
   `test -e  pending_release_notes.md && kill -SIGHUP $pid || systemctl --user reload devpod`


devpod flatpak, specifically:

- Why flatpak?
  - OS support for flatpak and not for AppImage
  - https://www.google.com/search?q=compare+appimage+and+flatpak
- There's a podman-desktop flatpak; it depends upon the podman flatpak.
  - https://github.com/flathub/io.podman_desktop.PodmanDesktop/blob/master/io.podman_desktop.PodmanDesktop.yml
- The vscode flatpak has host-spawn and zypak:  
  https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml
  - https://github.com/1player/host-spawn
  - https://flatkill.org/2020/
- com.visualstudio.code.tool.podman wraps podman-remote; so that you don't need to pass the host or rootless user DOCKER_SOCKET through to the flatpak, you can just call podman-remote:
  https://github.com/flathub/com.visualstudio.code.tool.podman/blob/master/com.visualstudio.code.tool.podman.yml
- podman-remote:
  - https://docs.podman.io/en/latest/markdown/podman-remote.1.html
  - https://github.com/containers/podman/blob/main/docs/tutorials/remote_client.md
    > On the local operating system, when you execute a Podman command, Podman connects to the server via SSH. It then connects to the Podman service by using systemd socket activation, and hitting our Rest API. The Podman commands are executed on the server. From the client's point of view, it seems like Podman runs locally.
