### ISSUE TITLE
[Docker] support cloning into volumes

### ISSUE THREAD

**Issue by shyim** [loft-sh/devpod#708]
**Is your feature request related to a problem?**  
Host mounts are really slow and break maybe if the software requires a real linux filesystem. Also any Jetbrains IDE will complain on Windows with Docker Desktop that the Filesystem mount is too slow.

**Which solution do you suggest?**  

When I enter a URL / local folder to devpod, clone/copy it contents to an docker volume and mount this instead of doing a host filesystem mount.
Like vscode does with devcontainer plugin: https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_use-clone-repository-in-container-volume

**Comment by pascalbreuninger** [comment]
Hi @shyim, that's a known problem. We've had a discussion about this in [this ticket](https://github.com/loft-sh/devpod/issues/549). Would moving your source code to WSL work for you?

**Comment by shyim** [comment]
It's a workaround, but not an fix.

**Comment by pascalbreuninger** [comment]
I'm hesitant to go ahead with this because you'd loose the sync with the os folder. Specially for local docker that's one of the major benefits. 
Did you try to apply the steps outlined in the vs code docs?

**Comment by QAston** [comment]
I'm having the same concern, I would like to use devcontainer for the entire team (windows, mac and linux), I'm testing this on windows and the host mount is really slow.

While I guess I could go with WSL on windows, presumably that's not an option on Macs, do you have any solutions there? Regular devcontainer runtime uses a volume instead of a bindmount if you give it a repository, which should be much faster on both operating systems, and would solve priviledge mismatches if any.

**Comment by QAston** [comment]
I worked around the issue by simply not working in the workspace directory created, but in an additional volume created in the devcontainer mounts section.
