### ISSUE TITLE
expose telemetry setting

### ISSUE THREAD

**Issue by 8de2fdb0** [loft-sh/devpod#890]
**Is your feature request related to a problem?**  

No

**Which solution do you suggest?**  

1. Add a toggle to disable telemetry in the settings menu.

2. Check telemetry settings inside the `github.com/loft-sh/devpod/pkg/telemetry"` package to make sure it is always respected.
Currently it is only checked in the `config` package. 

3. Consider telemetry an opt in.

**Which alternative solutions exist?**  

**Additional context**  

The telemetry option
https://github.com/loft-sh/devpod/blob/b07fa85cf2e6bedc4cad1131e97899dda2a9b3ff/pkg/config/config.go#L269

Telemetry setting is not honnored in this file.
https://github.com/loft-sh/devpod/blob/main/cmd/root.go#L40

**Comment by pascalbreuninger** [comment]
Hi @8de2fdb0 , thanks for raising this issue.
As always, telemetry is a bit of a hot topic in open source projects. 

The `TELEMETRY` context is currently being respected because without the `RecordStartEvent`, `RecordEndEvent` won't send anything to the analytics server. 
We are very open about the data we collect and you can read all about it [here](https://devpod.sh/docs/other-topics/telemetry). I want to re-emphasize that we **do not send any actual values**, just the commands that are invoked and which flags are being used. There is an example payload on the documentation page that you can go through to verify this. 

We'll add a opt-out button into the UI to make it easier for you, like you suggested.
